# Configurations
title: This is Content Organized
description: A digital personal knowledgebase garde ;) 
baseurl: "" # the subpath of your site, e.g. /blog

url: "https://colofon.mateu.me" # the base hostname & protocol for your site, e.g. http://example.com

remote_theme: pmarsceill/just-the-docs

permalink: pretty


# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"

# Assets and Images 
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Enable or disable the site search
# Supports true (default) or false
search_enabled: false
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Enable or disable heading anchors
heading_anchors: true

aux_links:
  "Microblog":
    - "https://r.mateu.me"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false


# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# Footer content
# appears at the bottom of every page's main content

# Back to top link
# back_to_top: true
# back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2021 Roberto Mateu."



# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
# ga_tracking: UA-2709176-10
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

plugins:
  - jekyll-seo-tag
  - jekyll-feed
